import itertools
import os

import matplotlib.pyplot as plt
from astropy.table import Table, join, hstack
import numpy as np

import band_conversions as conv
import photometry as phot
import statop as stat

FSPS_PATH = "/home/regulus/simonian/year1/fsps"
OUTPUT_PATH = os.path.join(FSPS_PATH, "OUTPUTS")
TBURST_PATH = os.path.join(OUTPUT_PATH, "tburst_change")
MET_DIR = os.path.join(OUTPUT_PATH, "met_change")

ALL_COLORS = [("FUV", "NUV"), ("NUV", "J"), ("J", "Ks"), ("Ks", "W1"), 
              ("W1", "W2"), ("W2", "W3"), ("W3", "W4")]

def read_mags(magfile, extinction=""):
    '''Reads in the raw magnitude file generated by FSPS.

    This function will read in the entries given in the mags file. The
    quantities which are not magnitudes will be given as base 10 logs in order
    to prevent over/underflows for some reason.

    The extinction flag will allow an extinction table to be used. Currently,
    the extinction table should be output in the form of an IPAC table from the
    IRSA Dust Extinction Service.
    '''
    # There may be a way to have the extinction pulled from the server. But
    # this will not be important in the short-term.
    magtable = Table.read(magfile, format="ascii.no_header")
    rename_mag_table(magtable)
    useful_table = filter_mag_table(magtable)
    return useful_table

def read_specs(specfile, extinction=""):
    '''Reads in the raw spectrum generated by FSPS.

    This function will read in all of the entries in the spec file. The first
    four columns will be the logarithm of the age, mass, bolometric luminosity,
    and star formation rate (with units of years, solar masses, solar
    luminosities, and solar masses per year, respectively). The columns
    afterward will be the spectra with the column name being a string
    representation of the wavelength in Angstroms. 

    Extinction may or may not be implemented at some later date.
    '''
    f = open(specfile, 'r')
    fullfile = f.readlines()
    specfile = fullfile[9::2]
    infofile = fullfile[10::2]

    spectable = Table.read(specfile, format="ascii.basic")
    infotable = Table.read(
        infofile, format="ascii.no_header", 
        names=("log(age)", "log(mass)", "log(lbol)", "log(SFR)"))

    fulltable = hstack([infotable, spectable])
    return fulltable

def rename_mag_table(magtable):
    '''Renames the columns from a just-read magnitude table.

    The magtable doesn't contain the names for the columns, so they will be put
    in post-hoc. Note that this changes the original table, it does not return
    a table.'''

    for column_name in magtable.colnames:
        colnum = strip_colnumber(column_name)
        if colnum == 1:
            newcolname = "log(age)"
        elif colnum == 2:
            newcolname = "log(mass)"
        elif colnum == 3:
            newcolname = "Log(lbol)"
        elif colnum == 4:
            newcolname = "log(SFR)"
        else:
            newcolname = "filter{0:d}".format(colnum-4)
        magtable.rename_column(column_name, newcolname)

def filter_mag_table(magtable):
    '''Filters the entries from the magnitude table that we want.

    These entries will namely be age, W1, W2, W3, W4, NUV, and FUV.
    '''
    newtable = Table([10**magtable["log(age)"], 10**magtable["log(SFR)"],
                      magtable["filter10"], magtable["filter11"], 
                      magtable["filter12"], magtable["filter83"], 
                      magtable["filter84"], magtable["filter85"], 
                      magtable["filter86"], magtable["filter62"], 
                      magtable["filter63"]], 
                     names=("Age", "SFR", 
                            "J", "H", "Ks", 
                            "W1", "W2", "W3", "W4", 
                            "FUV", "NUV"))
    return newtable


def strip_colnumber(col):
    '''Strips the column number from a default column name.

    All column names are named by col[X] where X is the column number starting
    with col1 and up to the number of columns. This function extracts X as an
    integer.
    '''
    return int(col[3:])

def plot_model_vs_data(modelx, modely, datax, datay, datayerr, dataxerr=None,
                       title="Title", xlabel="X axis", ylabel="Y axis",
                       datalabel="Data", modellabel="Model"):
    '''Makes a basic model v. data plot.

    The model values should be given, and they will be plotted as a continuous
    curve. The data points will be given with errors. X errors are allowed.

    The title, xlabel, ylabel, as well as labels for the data and model are
    also permitted.
    '''
    plt.plot(modelx, modely, label=modellabel)
    plt.errorbar(datax, datay, datayerr, dataxerr, label=datalabel)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()

def color_age_plot(modelcolor, modelage, datacolor=None, dataage=None,
                   dataerr=None, ageerr=None, title="Color-Age plot", 
                   xlabel="Age (Gyr)", ylabel="Color", datalabel="Data", 
                   modellabel="Model"):
    '''Plots a model line versus data.

    The y value and x value for the model are required. Data are optional. The
    options for the plot are self-explanatory.
    '''
    plt.plot(modelage, modelcolor, label=modellabel)
    if (datacolor is not None) and (dataage is not None):
        plt.errorbar(dataage, datacolor, dataerr, ageerr)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)

def tburst_data_plot(times, lowmet, highmet, atlas3dtable, 
                     TBURST_DIR=TBURST_PATH, MET_PATH=MET_DIR, 
                     met_fileformat="z{0:+3.2f}.mags", 
                     t_fileformat="low_tau{0:02d}.mags", 
                     title="Burst Evolution", t_label="{0} Gyr",
                     met_label="[Z/H]={0:.2f}", loc="upper right", SSPfile="", 
                     bands=ALL_COLORS, zh_split=0.0, 
                     burst_colors=['k', 'g', 'y', 'c', 'm']):
    '''Makes a plot showing different values of tburst.

    Times should be a list of ages that should be evaluated in Gyr. Currently,
    integer values between 1 and 15 are acceptable. TBURST_DIR is where the
    files holding the tburst variation parameters are located. The fileformat
    argument specifies the format of the file as found in TBURST_DIR. The
    string should accept a single formatted argument, which would be the
    current iteration through the times variable. Bands should be a list of 
    2-tuples containing the band names to be used as colors. See the 
    ALL_COLORS global variable for the format of bands. The color as plotted
    will be in the burst_colors list. This is to avoid conflicts with other
    color conventions.

    Data is passed through the atlas3dtable variable. The data will be
    color-coded according to metallicity. For data with "z/h" value greater
    than that provided by the zh keyword, the data will be red. Otherwise, the
    data will be blue.
    
    Metallicity bounds will also be included from models in the MET_PATH
    directory. There will be a lower metallicity track, which will be labeled
    in blue, and a high metallicity track, which will be labeled in red. This
    color scheme should be compatible with that of the data.

    The title will essentially be the title of the plot. label will be the
    string to be displayed in the legend. And loc will be passed to the legend 
    command to place it.'''
    for blueband, redband in bands:
        plt.figure()
        # If we desire an SSP, it will be added.
        if SSPfile:
            filename = os.path.join(TBURST_DIR, "ssp.mags")
            magtable = read_mags(filename)
            plt.plot(magtable["Age"]/1e9, magtable[blueband] - magtable[redband],
                     label="SSP")
        # Make the tracks for desired times.
        plot_tburst_tracks(times, TBURST_DIR, blueband, redband, t_fileformat,
                           t_label, burst_colors)
        plot_metallicity_bounds(lowmet, highmet, MET_PATH, blueband, redband,
                                met_fileformat, met_label)
        # Now add on the data.
        color, colorerr = stat.calc_statistical_difference(
            atlas3dtable[phot.name_photometry_column(blueband)], 
            atlas3dtable[phot.name_photometry_column(redband)],
            atlas3dtable[phot.name_photometry_column(blueband, error=True)],
            atlas3dtable[phot.name_photometry_column(redband, error=True)])
        plot_atlas3d_coded_by_metallicity(atlas3dtable["age"], color, 
                                          colorerr, atlas3dtable["age_err"],
                                          atlas3dtable["z/h"], 
                                          zh_lim=zh_split)
        plt.title(title)
        plt.xlabel("Age (Gyr)")
        plt.ylabel("{0}-{1}".format(blueband, redband))
        plt.legend(loc=loc)

def plot_metallicity_bounds(lowzh, highzh, MET_PATH, blueband, redband,
                            fileformat="z{0:+3.2f}.mags", 
                            label="[Z/H]={0:.2f}"):
    '''Plots FSPS tracks at metallicity bounds.'''
    lowmetfilename = os.path.join(MET_PATH, fileformat.format(lowzh))
    lowmetmagtable = read_mags(lowmetfilename)
    highmetfilename = os.path.join(MET_PATH, fileformat.format(highzh))
    highmetmagtable = read_mags(highmetfilename)
    plt.plot(lowmetmagtable["Age"]/1e9, lowmetmagtable[blueband] -
             lowmetmagtable[redband], 'b-', label=label.format(lowzh))
    plt.plot(highmetmagtable["Age"]/1e9, highmetmagtable[blueband] -
             highmetmagtable[redband], 'r-', label=label.format(highzh))

def plot_dust_toggled_metallicity_bounds(FILE_PATH, blueband, redband,
                                        highdusthighmet="dust_highmet.mags",
                                        highdustlowmet="dust_lowmet.mags",
                                        lowdusthighmet="nodust_highmet.mags",
                                        lowdustlowmet="nodust_lowmet.mags",
                                        highmet=0.2, lowmet=-0.89,
                                        dustsuffix="", 
                                        nodustsuffix=" (No dust)"):
    '''Plots two FSPS metallicity bounds for dusty and dustless galaxies.

    This function is kinda contrived and not elegant at all. But oh well, I
    think that's the price I pay for not making a super legit FORTRAN routine,
    or just runnings FSPS over and over and over again.'''
    highdusthighmetfilename = os.path.join(FILE_PATH, highdusthighmet)
    highdusthighmettable = read_mags(highdusthighmetfilename)
    highdustlowmetfilename = os.path.join(FILE_PATH, highdustlowmet)
    highdustlowmettable = read_mags(highdustlowmetfilename)
    lowdustlowmetfilename = os.path.join(FILE_PATH, lowdustlowmet)
    lowdustlowmettable = read_mags(lowdustlowmetfilename)
    lowdusthighmetfilename = os.path.join(FILE_PATH, lowdusthighmet)
    lowdusthighmettable = read_mags(lowdusthighmetfilename)

    highdusthighmetlabel="[Z/H]={0:.2f}{1}".format(highmet, dustsuffix)
    highdustlowmetlabel="[Z/H]={0:.2f}{1}".format(lowmet, dustsuffix)
    lowdusthighmetlabel="[Z/H]={0:.2f}{1}".format(highmet, nodustsuffix)
    lowdustlowmetlabel="[Z/H]={0:.2f}{1}".format(lowmet, nodustsuffix)

    plt.plot(highdusthighmettable["Age"]/1e9, highdusthighmettable[blueband] -
             highdusthighmettable[redband], 'r-', label=highdusthighmetlabel)
    plt.plot(highdustlowmettable["Age"]/1e9, highdustlowmettable[blueband] -
             highdustlowmettable[redband], 'b-', label=highdustlowmetlabel)
    plt.plot(lowdusthighmettable["Age"]/1e9, lowdusthighmettable[blueband] -
             lowdusthighmettable[redband], 'r--', label=lowdusthighmetlabel)
    plt.plot(lowdustlowmettable["Age"]/1e9, lowdustlowmettable[blueband] -
             lowdustlowmettable[redband], 'b--', label=lowdustlowmetlabel)

def plot_tburst_tracks(times, TBURST_DIR, blueband, redband, 
                       fileformat="early_t{0:02d}.mags", label="{0} Gyr",
                       fmts=['k', 'g', 'y', 'c', 'm']):
    '''Plots FSPS tburst model data.'''
    for i, fmt in zip(times, fmts):
        filename = os.path.join(TBURST_DIR, fileformat.format(i))
        magtable = read_mags(filename)
        plt.plot(magtable["Age"]/1e9, magtable[blueband] - 
                 magtable[redband], fmt, label=label.format(i))

def plot_atlas3d_coded_by_metallicity(xvalues, yvalues, yerrs, xerrs, ylims, zh, 
                                      zh_lim=0.0):
    '''Plots atlas3d points so that they are color-coded by metallicity.

    This function will ONLY plot points such that those with [Z/H] values as
    determined by SSP models higher than the provided zh value will be red,
    while those with lower metallicities will be blue. By default, zh
    corresponds to solar metallicity. The atlas3dtable will require a column
    named "z/h".
    '''
    highmetindices = np.where(zh >= zh_lim)
    lowmetindices = np.where(zh < zh_lim)
    highmetx, highmety = xvalues[highmetindices], yvalues[highmetindices]
    lowmetx, lowmety = xvalues[lowmetindices], yvalues[lowmetindices]
    highmetxerr, highmetyerr = xerrs[highmetindices], yerrs[highmetindices]
    lowmetxerr, lowmetyerr = xerrs[lowmetindices], yerrs[lowmetindices]
    highmetlims = ylims[highmetindices]
    lowmetlims = ylims[lowmetindices]
    
    stat.errorbar(highmetx, highmety, highmetyerr, highmetxerr, highmetlims, 
                  'r.', label="[Z/H] >= {0:.1f}".format(zh_lim), ufmt='rv', 
                  lfmt='r^')
    stat.errorbar(lowmetx, lowmety, lowmetyerr, lowmetxerr, lowmetlims, 'b.',
                  label="[Z/H] < {0:.1f}".format(zh_lim), ufmt='bv', lfmt='r^')


def color_difference_plot(times, outputdir=TBURST_PATH, prefix1="early_t",
                          colorsuff1="", prefix2="noagbdust_t",
                          colorsuff2=" (No dust)", title="Dust Difference", 
                          label="{0} Gyr", loc="upper right", 
                          bands=ALL_COLORS):
    '''Plots the color difference between two classes of models.

    Times should be a list of ages that should be evaluated in Gyr. Integer
    values between 1 and 15 are acceptable. outputdir is the directory where
    the files holding the output variation are located. The first prefix
    indicates the class of models which will be left of the subtraction sign
    (minuend), and the second prefix indicates the class which will be on the
    right (subtrahend). The colorsuffs are suffixes which will be printed
    after the colors on the y-axis label. For example, the default colorsuff
    will yield (W1-W2)-(W1-W2)_nodust. The bands keyword should be a list of
    tuples representing the color of the band. For an explicit example, see the
    ALL_COLORS constant in this file.

    The title will be the title of the plot. Label will be formatted to have
    the current value in the time array as the first argument. Loc will be
    passed to the legend command to place the legend.'''
    for  blueband, redband in bands:
        plt.figure()
        for i, t in enumerate(times):
            topfile = os.path.join(outputdir, 
                                    "{0}{1:02d}.mags".format(prefix1, t))
            toptable = read_mags(topfile)
            bottomfile = os.path.join(outputdir, 
                                    "{0}{1:02d}.mags".format(prefix2, t))
            bottomtable = read_mags(bottomfile)

            if not np.array_equal(bottomtable["Age"], toptable["Age"]):
                raise ValueError("FSPS model ages do not match!")
            else:
                ages = bottomtable["Age"]
            topcolor = toptable[blueband] - toptable[redband]
            bottomcolor = bottomtable[blueband] - bottomtable[redband]
            colordiff = topcolor - bottomcolor
            linecolor = plt.rcParams["axes.color_cycle"][i]
            plt.plot(ages/1e9, topcolor, '-', label=label.format(t)+colorsuff1,
                     color=linecolor)
            plt.plot(ages/1e9, bottomcolor, ':',
                     label=label.format(t)+colorsuff2,
                     color=linecolor)
            plt.title(title)
            plt.xlabel("Age (Gyr)")
            plt.ylabel("({0}-{1})".format(blueband, redband))
            plt.legend(loc=loc)

def Astropy_Table_to_numpy_array(table, dtype=np.float64):
    '''Converts an Astropy table to a 2-D numpy array.

    NOTE: This requires all of the entries in the table to be of the given
    dtype.
    '''
    data = np.ma.array(table)
    arr = data.view(dtype).reshape(len(data), len(data.dtype))
    return arr

def mag_table_to_flux_table(
    table, runbands=(conv.WISE_bands + conv.TWOMASS_bands + conv.GALEX_bands),
    ZP="AB"):
    '''Converts a table in magnitudes to a table in fluxes.'''
    mag_columns = [phot.name_photometry_column(band, error=False) for band in
                   runbands]
    err_columns = [phot.name_photometry_column(band, error=True) for band in
                   runbands]
    newtable = table[["objstr_01"]]
    for band in runbands:
        mag_column = phot.name_photometry_column(band, error=False)
        err_column = phot.name_photometry_column(band, error=True)
        if ZP is "AB":
            newtable[mag_column] = conv.ABmag2Jansky(band, table[mag_column])
        elif ZP is "Vega":
            newtable[mag_column] = conv.Vegamag2Jansky(band, table[mag_column])
        else:
            raise ValueError("Don't understand magnitude system: "
                             "{0}.".format(ZP))
        newtable[err_column] = conv.Mag_err_to_Jansky_err(
            band, table[mag_column], table[err_column])
    return newtable

def normalize_magnitude_SED(SED, normvalue, runbands, normband):
    '''Normalizes the SED to have magnitude equal to normvalue at normband.'''
    normindex = runbands.index(normband)
    normed_SED = SED - SED[normindex] + normvalue
    return normed_SED

def normalize_flux_SED(SED, normvalue, wavelengths, normband):
    '''Normalizes the SED to have flux equal to normvalue at normband.
    
    This is a little bit tricky because flux SEDs don't necessary coincide with 
    '''
    pass


def plot_data_SED(
        datatable, label="Data", fmt="r.", 
        runbands=(conv.WISE_bands + conv.TWOMASS_bands + conv.GALEX_bands),
        normband="Ks", normvalue=1, inputzp="AB", plotquant="Flux"):
    # In order to make a plot of nu-fnu, we need fluxes.
    if plotquant is "Flux":
        datatable = mag_table_to_flux_table(datatable, runbands=runbands,
                                            ZP=inputzp)
    elif plotquant is not "Mag":
        raise ValueError("Don't understand what quantity to plot.")
    # Wavelengths in microns
    wavelengths = np.array([conv.WAVELENGTHS[band] for band in runbands])*1e6
    frequencies = 3e14 / wavelengths
    mag_columns = [phot.name_photometry_column(band, error=False) for band in
                   runbands]
    err_columns = [phot.name_photometry_column(band, error=True) for band in
                   runbands]

    data_arr = Astropy_Table_to_numpy_array(datatable[mag_columns])
    sed_table = Table(data_arr.transpose(), names=datatable["objstr_01"])
    data_err_arr = Astropy_Table_to_numpy_array(datatable[err_columns])
    sed_err_table = Table(data_err_arr.transpose(), 
                          names=datatable["objstr_01"])

    for gal in sed_table.colnames:
        galaxy_sed = sed_table[gal]
        galaxy_sed_err = sed_err_table[gal]
        # If we change to fluxes, we want to plot nu-fnu.
        if plotquant is "Flux":
            galaxy_sed *= frequencies
            galaxy_sed_err *= frequencies
        normindex = runbands.index(normband)
        # This norming is all wrong. There shoul be two separate cases for
        # magnitudes and fluxes.
        normed_sed = galaxy_sed / galaxy_sed[normindex] * normvalue
        normed_sed_err = galaxy_sed_err / galaxy_sed[normindex] * normvalue
        plt.errorbar(wavelengths, normed_sed, normed_sed_err, fmt=fmt,
                     label=label)

def plot_FSPS_SED(
        FSPS_DIR, modelbase="SSP.out", label="FSPS", fmt="c*",  
        runbands=(conv.WISE_bands + conv.TWOMASS_bands + conv.GALEX_bands),
        ageindex=-1, normband="Ks", plotquant="Flux"):
    '''Plots a model FSPS SED with data.

    Takes an FSPS directory and file with a table full of data, and then plots
    both as an SED.
    '''
    wavelengths = np.array([conv.WAVELENGTHS[band] for band in runbands])*1e6
    #frequencies = 3e14 / wavelengths

    if plotquant is "Mag":
        filepath = os.path.join(
            FSPS_DIR, "OUTPUTS", ".".join([modelbase, "mags"]))
        magtable = read_mags(filepath)

        mags = np.array([magtable[ageindex][band] for band in runbands])
        normindex = runbands.index(normband)
    elif plotquant is "Flux":
        filepath = os.path.join(
            FSPS_DIR, "OUTPUTS", ".".join(modelbase, "spec"))
        fluxtable = read_specs(filepath)
    else:
        raise ValueError(
            "plotquant must be either Flux or Mag, not {0}".format(plotquant))

    plt.semilogx(wavelengths, mags, fmt, label=label)

    print magtable["Age"][ageindex]
    return mags[normindex]

