

from astropy.table import Table

def read_mags(magfile):
    '''Reads in the raw magnitude file generated by FSPS.

    This function will read in the entries given in the mags file. The
    quantities which are not magnitudes will be given as base 10 logs in order
    to prevent over/underflows for some reason.
    '''
    magtable = Table.read(magfile, format="ascii.no_header")
    rename_mag_table(magtable)

def rename_mag_table(magtable):
    '''Renames the columns from a just-read magnitude table.

    The magtable doesn't contain the names for the columns, so they will be put
    in post-hoc. Note that this changes the original table, it does not return
    a table.'''

    for column_name in magtable.colnames:
        colnum = strip_colnumber(column_name)
        if colnum == 1:
            newcolname = "log(age)"
        elif colnum == 2:
            newcolname = "log(mass)"
        elif colnum == 3:
            newcolname = "Log(lbol)"
        elif colnum == 4:
            newcolname = "log(SFR)"
        else:
            newcolname = "filter{0:d}".format(colnum-4)
        magtable.rename_column(column_name, newcolname)


def strip_colnumber(col):
    '''Strips the column number from a default column name.

    All column names are named by col[X] where X is the column number starting
    with col1 and up to the number of columns. This function extracts X as an
    integer.
    '''
    return int(col[3:])
