import os

import matplotlib.pyplot as plt
from astropy.table import Table, join
import numpy as np

import band_conversions as conv

FSPS_PATH = "/home/regulus/simonian/year1/fsps"
OUTPUT_PATH = os.path.join(FSPS_PATH, "OUTPUTS")
TBURST_PATH = os.path.join(OUTPUT_PATH, "tburst_change")
MET_DIR = os.path.join(OUTPUT_PATH, "met_change")

ALL_COLORS = [("FUV", "NUV"), ("NUV", "W1"), ("W1", "W2"), ("W2", "W3"), 
              ("W3", "W4")]

def read_mags(magfile, extinction=""):
    '''Reads in the raw magnitude file generated by FSPS.

    This function will read in the entries given in the mags file. The
    quantities which are not magnitudes will be given as base 10 logs in order
    to prevent over/underflows for some reason.

    The extinction flag will allow an extinction table to be used. Currently,
    the extinction table should be output in the form of an IPAC table from the
    IRSA Dust Extinction Service.
    '''
    # There may be a way to have the extinction pulled from the server. But
    # this will not be important in the short-term.
    magtable = Table.read(magfile, format="ascii.no_header")
    rename_mag_table(magtable)
    useful_table = filter_mag_table(magtable)
    return useful_table

def rename_mag_table(magtable):
    '''Renames the columns from a just-read magnitude table.

    The magtable doesn't contain the names for the columns, so they will be put
    in post-hoc. Note that this changes the original table, it does not return
    a table.'''

    for column_name in magtable.colnames:
        colnum = strip_colnumber(column_name)
        if colnum == 1:
            newcolname = "log(age)"
        elif colnum == 2:
            newcolname = "log(mass)"
        elif colnum == 3:
            newcolname = "Log(lbol)"
        elif colnum == 4:
            newcolname = "log(SFR)"
        else:
            newcolname = "filter{0:d}".format(colnum-4)
        magtable.rename_column(column_name, newcolname)

def filter_mag_table(magtable):
    '''Filters the entries from the magnitude table that we want.

    These entries will namely be age, W1, W2, W3, W4, NUV, and FUV.
    '''
    newtable = Table([10**magtable["log(age)"], 10**magtable["log(SFR)"],
                      magtable["filter10"], magtable["filter11"], 
                      magtable["filter12"], magtable["filter83"], 
                      magtable["filter84"], magtable["filter85"], 
                      magtable["filter86"], magtable["filter62"], 
                      magtable["filter63"]], 
                     names=("Age", "SFR", 
                            "J", "H", "Ks", 
                            "W1", "W2", "W3", "W4", 
                            "FUV", "NUV"))
    return newtable


def strip_colnumber(col):
    '''Strips the column number from a default column name.

    All column names are named by col[X] where X is the column number starting
    with col1 and up to the number of columns. This function extracts X as an
    integer.
    '''
    return int(col[3:])

def plot_model_vs_data(modelx, modely, datax, datay, datayerr, dataxerr=None,
                       title="Title", xlabel="X axis", ylabel="Y axis",
                       datalabel="Data", modellabel="Model"):
    '''Makes a basic model v. data plot.

    The model values should be given, and they will be plotted as a continuous
    curve. The data points will be given with errors. X errors are allowed.

    The title, xlabel, ylabel, as well as labels for the data and model are
    also permitted.
    '''
    plt.plot(modelx, modely, label=modellabel)
    plt.errorbar(datax, datay, datayerr, dataxerr, label=datalabel)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()

def color_age_plot(modelcolor, modelage, datacolor=None, dataage=None,
                   dataerr=None, ageerr=None, title="Color-Age plot", 
                   xlabel="Age (Gyr)", ylabel="Color", datalabel="Data", 
                   modellabel="Model"):
    '''Plots a model line versus data.

    The y value and x value for the model are required. Data are optional. The
    options for the plot are self-explanatory.
    '''
    plt.plot(modelage, modelcolor, label=modellabel)
    if (datacolor is not None) and (dataage is not None):
        plt.errorbar(dataage, datacolor, dataerr, ageerr)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)

def tburst_data_plot(times, TBURST_DIR=TBURST_PATH, prefix="early_t", 
                title="Burst Evolution", label="{0} Gyr", loc="upper right",
                SSPfile = "SSP.mags", bands=ALL_COLORS):
    '''Makes a plot showing different values of tburst.

    Times should be a list of ages that should be evaluated in Gyr. Currently,
    integer values between 1 and 15 are acceptable. TBURST_DIR is where the
    files holding the tburst variation parameters are located. The prefix
    specifies the fixed prefix that describes the filename. It will be followed
    by a formatted version of the age, and then an extension. Therefore, for
    the default 3Gyr file, the filename will be "early_t03.mags". Bands should
    be a list of 2-tuples containing the band names to be used as colors. See
    the ALL_COLORS global variable for the format of bands.
    
    The title will essentially be the title of the plot. label will be the
    string to be displayed in the legend. And loc will be passed to the legend 
    command to place it.'''
    for blueband, redband in bands:
        plt.figure()
        filename = os.path.join(TBURST_DIR, "ssp.mags")
        magtable = read_mags(filename)
        plt.plot(magtable["Age"]/1e9, magtable[blueband] - magtable[redband],
                 label="SSP")
        for i in times:
            filename = os.path.join(TBURST_DIR, 
                                    "{0}{1:02d}.mags".format(prefix, i))
            magtable = read_mags(filename)
            plt.plot(magtable["Age"]/1e9, magtable[blueband] - magtable[redband],
                     label=label.format(i))
        plt.title(title)
        plt.xlabel("Age (Gyr)")
        plt.ylabel("{0}-{1}".format(blueband, redband))
        plt.legend(loc=loc)

def color_difference_plot(times, outputdir=TBURST_PATH, prefix1="early_t",
                          colorsuff1="", prefix2="noagbdust_t",
                          colorsuff2=" (No dust)", title="Dust Difference", 
                          label="{0} Gyr", loc="upper right", 
                          bands=ALL_COLORS):
    '''Plots the color difference between two classes of models.

    Times should be a list of ages that should be evaluated in Gyr. Integer
    values between 1 and 15 are acceptable. outputdir is the directory where
    the files holding the output variation are located. The first prefix
    indicates the class of models which will be left of the subtraction sign
    (minuend), and the second prefix indicates the class which will be on the
    right (subtrahend). The colorsuffs are suffixes which will be printed
    after the colors on the y-axis label. For example, the default colorsuff
    will yield (W1-W2)-(W1-W2)_nodust. The bands keyword should be a list of
    tuples representing the color of the band. For an explicit example, see the
    ALL_COLORS constant in this file.

    The title will be the title of the plot. Label will be formatted to have
    the current value in the time array as the first argument. Loc will be
    passed to the legend command to place the legend.'''
    for  blueband, redband in bands:
        plt.figure()
        for i, t in enumerate(times):
            topfile = os.path.join(outputdir, 
                                    "{0}{1:02d}.mags".format(prefix1, t))
            toptable = read_mags(topfile)
            bottomfile = os.path.join(outputdir, 
                                    "{0}{1:02d}.mags".format(prefix2, t))
            bottomtable = read_mags(bottomfile)

            if not np.array_equal(bottomtable["Age"], toptable["Age"]):
                raise ValueError("FSPS model ages do not match!")
            else:
                ages = bottomtable["Age"]
            topcolor = toptable[blueband] - toptable[redband]
            bottomcolor = bottomtable[blueband] - bottomtable[redband]
            colordiff = topcolor - bottomcolor
            linecolor = plt.rcParams["axes.color_cycle"][i]
            plt.plot(ages/1e9, topcolor, '-', label=label.format(t)+colorsuff1,
                     color=linecolor)
            plt.plot(ages/1e9, bottomcolor, ':',
                     label=label.format(t)+colorsuff2,
                     color=linecolor)
            plt.title(title)
            plt.xlabel("Age (Gyr)")
            plt.ylabel("({0}-{1})".format(blueband, redband)) 
            plt.legend(loc=loc)
