import os
import os.path
import subprocess
import shutil
import math
import itertools

import numpy as np
from pyraf import iraf
from astropy.io import fits
from astropy.table import Table

import photometry as phot
from mask_trimmer import MaskCMD

#SEXTRACTOR_DIR = "/home/gregory/work/sextractor"
SEXTRACTOR_DIR = "/home/regulus/simonian/year1/wise/sextractor"

def build_masks(
        BASEDIR, WISETable, threshold=0, runbands=None,
        foregroundbase="foreground", pixelmaskbase="bad_pixels", 
        outputbase="mask", maskconfig="", ignore_exception=False, 
        overwrite=True, regionbase="ellipseregion"):
    '''Builds masks for specified objects.

    The objects to be built should be specified in WISETable, which should be a
    valid parameter construction file. Masks will be generated for all maskbands
    given in runbands. The default values for runbands is that given in
    phot.BANDS. The default distribution of masks is currently given by masking
    W1, copying that mask to W2-4, and then masking NUV, and possibly masking
    FUV if it uses a different file than NUV, otherwise copying it.

    Optional parameters are the threshold, which will override the value in the
    configuration file if it is nonzero, the name of the output, as well as the 
    config file. If the config file is left blank, an appropriate config file 
    located in SEXTRACTOR_DIR will be used instead.

    The resulting masks will written to $BASEDIR/{outputbase}.{maskband}.fits.
    '''
    # This is to prevent problems with referring to phot  before it's able to be
    # imported. This should be better organized...
    if not runbands:
        runbands=phot.bands
    # All WISE images should be identical. So just run one, and then copy-paste
    # the rest.
    for maskband in runbands:
        phot.allMasks(BASEDIR, WISETable, maskband, threshold=threshold, 
                      outputbase=outputbase, overwrite=overwrite,
                      ignore_exception=ignore_exception, regionbase=regionbase,
                      pixelmaskbase=pixelmaskbase, maskconfig=maskconfig)

def zero_all_masks(BASEDIR, WISEtable, outputmaskbase="nomask", runbands=None):
    '''See zero_masks'''
    # This is to prevent problems with referring to phot  before it's able to be
    # imported. This should be better organized...
    if not runbands:
        runbands=phot.bands
    phot.runOnImages(BASEDIR, WISEtable, zero_masks,
                     outputmaskbase=outputmaskbase, runbands=runbands)

def zero_masks(BASEDIR, WISErow, outputmaskbase="nomask", runbands=None):
    '''Creates a set of blank masks.

    This is useful for having a run of objects with no masking. The masks are
    generated by overwriting 0 on all of the pixels from the CCD images.'''
    # This is to prevent problems with referring to phot  before it's able to be
    # imported. This should be better organized...
    if not runbands:
        runbands=phot.bands
    galaxydir = phot.change_to_galaxy_dir(BASEDIR, WISErow["objstr_01"])
    command = "0"
    for band in runbands:
        inputfile = phot.match_filter(galaxydir, band)
        outputfile = phot.format_band_dependence(
            outputmaskbase, band, "fits", galaxydir)
        run_imcalc(inputfile, outputfile, command)

def run_sextractor(image, config, **options):
    '''Runs SExtractor on an image.

    The configuration file to be used can be specified through the config
    keyword.

    Other keywords to overwrite the configuration file parameters can be
    specified as additional keyword arguments.
    '''
    command = ["sex", image, "-c", config]
    print config
    # If I can't get rid of the threshold parameter, then I need to just delete
    # a nonsensical parameter.
    try:
        if options["DETECT_THRESH"] == 0:
            del(options["DETECT_THRESH"])
    except KeyError:
        pass
    for key, value in options.iteritems():
        command.append("-"+key)
        command.append(str(value))
    print "Running command: {0}".format(command)
    returncode = subprocess.call(command)
    if returncode:
        print returncode
        print "Could not run ''{0}''".format(' '.join(command))
        raise ValueError("Fatal Error in SExtractor.")

def all_foregrounds_to_mask(BASEDIR, WISEtable, runbands=None):
    '''Runs convert_foreground_to_mask on all entries in the WISEtable'''
    # This is to prevent problems with referring to phot  before it's able to be
    # imported. This should be better organized...
    if not runbands:
        runbands=phot.bands

    phot.runOnImages(BASEDIR, WISEtable, convert_foreground_to_mask, 
        runbands=runbands)

def convert_foreground_to_mask(BASEDIR, WISErow, runbands=None):
    '''Converts SEXtractor foreground masks into full invalid pixel masks.

    This is meant for legacy data sets where the invalid pixel masks need to be
    generated from foregound masks without automatically running the pipeline
    again.
    '''
    # This is to prevent problems with referring to phot  before it's able to be
    # imported. This should be better organized...
    if not runbands:
        runbands=phot.bands
    galaxydir = phot.change_to_galaxy_dir(BASEDIR, WISErow["objstr_01"])
    for band in runbands:
        bad_pixels = phot.format_band_dependence("badpixels", band, "fits", galaxydir)
        maskfile = phot.format_band_dependence("mask", band, "fits", galaxydir)
        invert_image(phot.match_filter(galaxydir, band, sky=True), bad_pixels)
        foregroundfile = phot.format_band_dependence("foreground", band, "fits", galaxydir)
        join_masks(foregroundfile, bad_pixels, maskfile)


def sextractor_background(image, config, **sexargs):
    '''Creates a background for an image.

    Gives a mesh with size of mesh_size to estimate the background, along with
    filtering it with filter_size.

    Relevant keyword arguments are:
    BACK_SIZE: Specifies the size of the background mesh.
    BACK_FILTERSIZE: Specifies how much filtering of the background is done.
    CHECKIMAGE_NAME: The location of the background file.
    '''
    sexargs["CHECKIMAGE_TYPE"] = "BACKGROUND"
    run_sextractor(image, config, **sexargs)

def sextractor_subtracted_background(image, config,
        output="subtracted.fits", mesh_size=480, filter_size=7):
    '''Creates a background-subtracted image.

    Gives a mesh with size of mesh_size to estimate the background, along with
    filtering it with filter_size.

    Relevant keyword arguments are:
    BACK_SIZE: Specifies the size of the background mesh.
    BACK_FILTERSIZE: Specifies how much filtering of the background is done.
    CHECKIMAGE_NAME: The location of the background file.
    '''
    sexargs["CHECKIMAGE_TYPE"] = "-BACKGROUND"
    run_sextractor(image, config, **sexargs)

def sextractor_mask(image, config, **sexargs):
    '''
    Creates a mask for an image.

    Uses a threshold value to determine whether an object is a foreground
    objects or part of the galaxy.

    Relevant keyword arguments are:
    DETECT_THRESH: The detection threshold for objects.
    THRESH_TYPE: How the detection threshold is defined.
    DETECT_MINAREA: The minimum area for an object to be detected.
    CHECKIMAGE_NAME: The location of the mask.
    '''
    sexargs["CHECKIMAGE_TYPE"] = "SEGMENTATION"
    run_sextractor(image, config, **sexargs)

def mask_algorithm(
        BASEDIR, WISErow, maskband="W1", threshold=0, 
        foregroundbase="foreground", pixelmaskbase="bad_pixels", 
        outputbase="mask", ellipsebase="ellipsepars", 
        regionbase="ellipseregions", spreadpix=5, maskconfig="", 
        overwrite=False):
    '''Creates a mask file for the object in WISErow.

    The general algorithm for the mask creation algorithm is to find bright
    stars outside of a radius given by r_high. It then finds stars outside of a
    radius given by the isophotal aperture times lowfrac. 
    
    This algorithm also handles GALEX images where only the central inner
    circle is considered a valid observation. 
    '''
    galaxydir = phot.change_to_galaxy_dir(BASEDIR, WISErow["objstr_01"])
    objectcoords = phot.getpixelcoords(phot.match_filter(galaxydir, maskband),
            WISErow["ra"], WISErow["dec"])
    foregroundfile = phot.format_band_dependence(
        foregroundbase, maskband, "fits", galaxydir)
    maskfile = phot.format_band_dependence(
        outputbase, maskband, "fits", galaxydir)
    # Add regionbase.
    if maskband in phot.IRBANDS and maskband is not "W1":
        shutil.copy(phot.format_band_dependence(outputbase, "W1", "fits",
            galaxydir), maskfile)
    elif maskband == "FUV" and (phot.match_filter(galaxydir, 
        "FUV").replace("-fd-", "-nd-") == phot.match_filter(galaxydir, "NUV")):
        shutil.copy(phot.format_band_dependence(outputbase, "NUV", "fits",
            galaxydir), os.path.join(galaxydir, maskfile))
        print "Copying NUV mask to FUV for {0}".format(WISErow["objstr_01"])
    else:
        # When done, add foregroundbase to other functions and change
        # outputbase to mask.
        mask_elliptical_galaxy(galaxydir, maskband, objectcoords, 
                               threshold=threshold, maskfile=foregroundfile, 
                               ellipsebase=ellipsebase, spreadpix=5, 
                               maskconfig=maskconfig, overwrite=overwrite, 
                               regionbase=regionbase)

        if maskband not in phot.IRBANDS and pixelmaskbase:
            # I'd like to add this to the GALEX pipeline rather than putting it
            # here. So instead of using the sky background value, we have a
            # specific image which contains invalid pixels. However, that sounds
            # like a lot of work. I could do it to another branch and then if I
            # have to redo the pipeline, merge it and go! In that case, I won't
            # make the inverted mask configurable... since it would just be a lot
            # of useless changing around.
            bad_pixels = phot.format_band_dependence(
                pixelmaskbase, maskband, "fits", galaxydir)
            invert_image(phot.match_filter(galaxydir, maskband, sky=True),
                     bad_pixels)
            join_masks(foregroundfile, bad_pixels, maskfile)
        else:
            shutil.copy(foregroundfile, maskfile)

def mask_elliptical_galaxy(
        galaxydir, maskband, objectcoords, threshold=5,
        maskfile="foregroundmask.fits", regionbase="ellipseregion",
        ellipsebase="ellipsepars", maskconfig="", segment="rawsegment.fits", 
        clearedsegment="segment_nogalaxy.fits",
        procsegment="foreground_unnormalized.fits",
        prespreadfile="foreground_normalized.fits", spreadpix=25,
        overwrite=False):
    '''Creates a foreground mask for an elliptical galaxy.

    This function uses the ellipse output to find the location of the ellipse
    and then remove it from the segmentation map, leaving us with a segmentation
   map of just the foreground objects.
   '''
    image = phot.match_filter(galaxydir, maskband)
    regionpath = phot.format_band_dependence(
        regionbase, maskband, "reg", galaxydir)
    if not maskconfig:
        maskconfig = select_sextractor_config(SEXTRACTOR_DIR, maskband, image)
    masked_image = os.path.join(galaxydir, segment)
    fullmask = os.path.join(galaxydir, maskfile)
    galaxy_removed = os.path.join(galaxydir, clearedsegment)
    segment_needs_normalization = os.path.join(galaxydir, procsegment)
    normalized_segment = os.path.join(galaxydir, prespreadfile)

    segmentation_mask(maskconfig, image, masked_image, 
                      segment_needs_normalization, objectcoords, 
                      threshold=threshold)
    # We'll interactively generate masks.
    print ("Please remove object {0} in "
        "{1}.".format(phot.extract_name_from_galaxy_dir(galaxydir), maskband))
    maskprog = MaskCMD(
        segment_needs_normalization, galaxy_removed, image, regionpath)
    maskprog.cmdloop()
    normalize_segmentation_map(galaxy_removed, normalized_segment)
    spreadmask(galaxydir, spreadpix, normalized_segment, outputfile=fullmask,
               overwrite=overwrite)

def spreadmask(workdir, pixels, maskimage, outputfile="foreground.fits",
               overwrite=False):
    '''Masks a square around each original pixel

    This function takes each of the pixels in maskimage and then masks a box
    with side length pixels around them.'''
    hdulist = fits.open(os.path.join(workdir, maskimage))
    origmask = hdulist[0].data
    mask_indices = np.transpose(np.nonzero(origmask))
    for coord in mask_indices:
        setedges(origmask, coord[0], coord[1], size=pixels, edgevalue=1)
    try:
        hdulist.writeto(os.path.join(workdir, outputfile), clobber=overwrite)
    except IOError:
        print "{0} already exists and overwrite disabled. Skipping.".format(
            outputfile)
    hdulist.close()
    
def setedges(fullarray, i, j, size=5, edgevalue=1):
    '''Takes a pixel at the center of fullarray and then sets all of the
    surrounding pixels within a box of side length size to edgevalue. For 
    example, a size of 5 would set all pixels within a distance of 2 pixels 
    from the center as edgevalue.

    It ignores edge cases.
    '''
    distance = (size-1) / 2
    for ib in range(-distance, distance+1):
        for jb in range(-distance, distance+1):
            try:
                fullarray[i+ib][j+jb] = edgevalue
            except IndexError:
                pass

def combinemasks(basefile, additionfile):
    '''Adds a mask to a base mask.'''
    run_imcalc([basefile, additionfile], basefile, 'im1 || im2')
    os.remove(additionfile)
    return basefile

def mask_check(BASEDIR, WISEtable, sigstart, sigend, sigstep, maskband="W1",
               maskbase="mask", skybase="sky_level", 
               ellipseoutput="ellipse_aperture", uncertaintybase="uncertainty",
               readonly=False):

    sigs = np.arange(sigstart, sigend, sigstep)
    mags = np.zeros(sigs.shape)
    errs = np.zeros(sigs.shape)

    for i,sig in enumerate(np.arange(sigstart, sigend, sigstep)):
        newmaskbase = sigify(maskbase, sig)
        newellipseaperture = sigify(ellipseoutput, sig)
        newskybase = sigify(skybase, sig)
        newuncertaintybase = sigify(uncertaintybase, sig)
        if not readonly:
            phot.build_pipeline(
                BASEDIR, WISEtable, maskthresh=sig, maskbase=newmaskbase, 
                skipmask=False, overwritemask=True, 
                ellipseoutput=newellipseaperture, skybase=newskybase,
                uncertaintybase=newuncertaintybase, runbands=[maskband], 
                ignore_exceptions=False)
            phot.generateEllipseCutouts(
                BASEDIR, WISEtable, runbands=[maskband], skyprefix=newskybase,
                aperturefile=newellipseaperture, maskbase=newmaskbase,
                suffix="{0}".format(sig))
        magtable = phot.aperture_photometry_table(
            BASEDIR, WISEtable["objstr_01"], runbands=[maskband],
            ellipseoutput=newellipseaperture, skybase=newskybase,
            uncertaintybase=newuncertaintybase, brightness="AB")
        mags[i] = magtable[
            phot.name_photometry_column(maskband, category="ap")][0]
        errs[i] = magtable[
            phot.name_photometry_column(
                maskband, error=True, category="ap")][0]

    return sigs, mags, errs

def sigify(basename, sig):
    '''Turns a basename into one which corresponds to a sigma value.'''
    return "{0}_{1}sig".format(basename, sig)

def subtractw3fromw1(config, w1image, w3image, w1output_nobackground, 
        w3output_nobackground, w3output_scaled, w1output_convolved, 
        subtracted_output, objcenter, central_radius):
    '''Subtracts the W3 background from W1 to accentuate point sources.'''
    # Generate W1 background-subtracted image.
    print "Subtracting W1 background."
    sextractor_subtracted_background(w1image, config,
            CHECKIMAGE_NAME=w1output_nobackground)
    # Generate W3 background-subtracted image.
    print "Subtracting W3 background."
    sextractor_subtracted_background(w3image, config,
            CHECKIMAGE_NAME=w3output_nobackground)
    # Convolve the W1 image.
    # Let's see if this causes the problems we expect it to.
    #print "Convolving W1 image."
    #run_gauss(w1output_nobackground, w1output_convolved, str(5 /
    #        phot.getPixelScale("W1")))
    shutil.copyfile(w1output_nobackground, w1output_convolved)
    # Find the mean values of the image centers
    # We're not actually using a radius. More of a box.
    bounds = "[{0}:{1},{2}:{3}]".format(objcenter[0] - central_radius,
            objcenter[0] + central_radius, objcenter[1] - central_radius,
            objcenter[1]+central_radius)
    w1mean = run_immean(w1output_convolved + bounds)
    w3mean = run_immean(w3output_nobackground + bounds)
    # Create the scaled W3 image.
    print "Scaling W3 image."
    run_imarith(w3output_nobackground, '*', str(w1mean / w3mean),
            w3output_scaled)
    # Subtract the two images.
    print "Subtracting images."
    run_imarith(w1output_convolved, '-', w3output_scaled, subtracted_output)

def segmentation_mask(config, image, masked_image, fullmask, coords, 
        threshold=5):
    '''Creates a mask from a segmentation image and object coordinates.

    SExtractor is only run once, but is used to generate a segmentation map.
    After generating the segmentation map, the object is looked up in the pixel
    coordinate of the image, and all matching pixel values are removed.

    The raw segmentation image is stored at masked_image and the segmentation
    image with the galaxyy removed is saved in fullmask, which is the desirable
    product.
    '''
    sextractor_mask(image, config, CHECKIMAGE_NAME=masked_image,
            DETECT_THRESH=threshold)
    remove_galaxy_from_mask(masked_image, fullmask, coords)

def remove_galaxy_from_mask(imagepath, newimagepath, coord):
    '''Removes a galaxy from a segmentation image.

    The coordinate of the galaxy in image pixels should be given. After that,
    the segmentation pixels corresponding to the galaxy will be removed from the
    image. The image without the galaxy segmentation patches will be saved to
    newimagepath.
    '''
    hdulist = fits.open(imagepath) 
    raw_mask = hdulist[0].data
    segment = find_segment(raw_mask, coord)
    new_mask = remove_segment(raw_mask, segment)
    newhdu = fits.PrimaryHDU(new_mask)
    try:
        newhdu.writeto(newimagepath)
    except IOError:
        os.remove(newimagepath)
        newhdu.writeto(newimagepath)
    
def remove_segment(image, number):
    '''Takes a FITS image and removes the region corresponding to the segment.

    The image should be a ndarray corresponding to the raw FITS image. The
    number should be the segmentation number we wish to remove from the image.
    It will be replaced with 0.
    '''
    segindices = np.where(image == number)
    image_copy = image.copy()
    image_copy[segindices] = 0
    return image_copy
        
def normalize_segmentation_map(image, output):
    '''Takes a segmentation map and sets all of the pixels to be either 1 or
    0.'''
    command = "if im1 then 1.0 else 0.0"
    run_imcalc(image, output, command, newformat="real")

def invert_image(image, output):
    '''Takes an image and inverts the pixels so that positive values become 0
    and 0s become 1s.'''
    command = "!im1"
    run_imcalc(image, output, command, newformat="real")

def join_masks(mask1, mask2, output):
    '''Joins two masks together using logical or operations.'''
    command = "im1 || im2"
    run_imcalc([mask1, mask2], output, command)

def clip_image(image, output, threshold):
    '''Sets all pixels lower than the given threshold to zero.'''
    command = "if im1 < {0} then 0.0 else im1".format(threshold)
    run_imcalc(image, output, command)

def find_segment(segimage, coord):
    '''Finds the SExtractor segment at a pixel value.

    This function uses the segmentation image to find the segmentation number of
    an object. The image should be passed as an ndarray, along with the
    coordinates in image pixel values.

    THE COORDINATES SHOULD NOT BE SPECIFIED AS NUMPY INDICES!
    '''
    return segimage[np.round(coord[1])-1, np.round(coord[0])-1]

def w1w3simulmask(config, w1image, w3image, w1initthresh, w3initthresh, 
        decfactor, diffactor, w1endthresh, w3threshfloor, masked_image, w1mask, 
        w3mask, accummask, iteration="geometric"):
    '''Masking algorithm which runs SExtractor on the w3 image to mask out the
    galaxy, and then uses the mask generated from the w3 image on the w1 image
    in order to capture Rayleigh-Jeans foreground sources.

    The algorithm starts out with w1initthresh and w3initthresh being given to 
    DETECT_THRESH in SExtractor. With each iteration, the threshold for w1 will
    decrease either arithmetically or geometrically by the decfactor, while the 
    threshold for w3 will decrease by decfactor * diffactor. The iterating 
    continues until the threshold for w1 drops below w1endthresh. In order to 
    deal with cases where the threshold for w3 would drop below zero if 
    diffactor is greater than 1, there will be a w3threshfloor argument which 
    bottoms out the value of w3. This should probably be at around 5 sigma.

    Each iteration will have the mask add on to accummask to preserve point
    sources which may be embedded in the galaxy. The location of the 
    intermediate w1 and w3 masks can be specified through the w1mask and w3mask
    arguments. The masked w1 image will be stored in masked_image.

    The effects of the parameters on the resulting mask can be roughly described
    as follows:
    w1initthresh: How sensitive the initial detection is. If you notice that
        flux from the center of the galaxy is being incorporated into the max,
        you may want to raise this. Note that raising this will also result in
        a longer computation.
    w3initthresh: How large the initial w1 mask is. If you notice that flux from
        the center of the galaxy is being incorporated into the mask, you may
        want to lower this. Additionally, if you notice that foreground stars
        close to the nucleus do not appear in the final mask, you will want to
        raise this.
    decfactor: How finely the iteration occurs. If you notice that foreground
        objects within the galaxy should be detected but aren't, you should 
        lower this value. Note: Lowering this value will also result in a longer
        computation.
    diffactor: How quickly the w3 mask increases over the w1 image. If you
        notice that objects embedded within the galaxy aren't being masked, then
        you should lower this value. However, if you notice that somewhere in
        the middle of the computation, the galaxy flux starts to appear in the
        final mask, you'll want to raise this value.
    w1endthresh: The ending threshold for w1. If you are not detecting faint
        enough objects, you will want to lower this. However, you don't want to
        lower it so far that it gets to be extremely difficult to avoid
        measuring galaxy flux.
    '''
    w1thresh = w1initthresh
    w3thresh= w3initthresh
    try:
        os.remove(accummask)
    except OSError:
        pass
    while w1thresh >= w1endthresh:
        if w3thresh <= w3threshfloor:
            w3thresh = w3threshfloor
        print "W1 threshold: {0}, W3 threshold: {1}".format(w1thresh, w3thresh)
        # Generate the W3 mask.
        sextractor_mask(w3image, w3thresh, config, maskoutput=w3mask)
        # Create the Masked W1 image.
        apply_mask(w1image, w3mask, masked_image)
        # Get the point sources from the masked W1 image.
        sextractor_mask(masked_image, w1thresh, config, maskoutput=w1mask)
        # Add the current mask to the accumulated mask.

        # We'll want to find a way to determine a better location for tempfile.
        # Probably through an argument.
        tempfile = "/home/regulus/simonian/year1/wise/sextractor_demo/NGC6946/tempmask.fits"
        try:
            run_imarith(accummask, '+', w1mask, tempfile)
            os.rename(tempfile, accummask)
        except OSError:
            print "Creating {0}.".format(accummask)
            os.rename(w1mask, accummask)
        if iteration is "arithmetic":
            w1thresh -= decfactor
            w3thresh -= decfactor * diffactor
        else:
            w1thresh /= decfactor
            w3thresh /= decfactor * diffactor
    print "Finished mask at {0}.".format(accummask)



def apply_mask(image, mask, outputfile):
    '''Applies a mask to an image.

    This will set all the pixels which are nonzero in the mask to be zero in the
    image. The masked file will then be located at outputfile.
    '''
    command = "if im2 then 0 else im1"
    run_imcalc([image, mask], outputfile, command)

def mask_circle(image, center, radius, outputfile):
    '''Masks a circular region of the image.

    The effect of this function is to set a circular region in an image to zero,
    thus effectively masking it. All numbers should be in units of pixels. The
    masked image will then be outputted into outputfile.
    '''
    xcenter, ycenter = center
    command = build_imcalc_circle(xcenter, ycenter, radius)
    run_imcalc(image, outputfile, command)

def mask_point_source(band, image, center, fill_value):
    '''Masks a point source on an image.

    Takes a coordinate and masks a circle with size of the typical FWHM of the
    PSF. The mask will be filled in with the fill_value.
    '''
    radius = phot.getPSFFWHM(band, pixel=True)
    mask_circle(image, center, radius, fill_value)

def mask_circle(image, center, radius, fill_value):
    '''Masks a circular region of the image

    This function sets the mask flag of an image that lies within a given 
    circle. The image should be a MaskedArray of some sort, center should be a
    tuple of x and y values, and radius should be the radius. 
    
    The center coordinates should be given as image indices (i.e. starting 
    from 1)
    '''
    xcenter, ycenter = center
    image_coords = np.indices(image.shape)
    circlemask = test_if_in_circle(
            image_coords[1], image_coords[0], xcenter-1, ycenter-1, radius)
    image[circlemask] = fill_value

def test_if_in_circle(x, y, xcenter, ycenter, radius):
    '''Tests if a point is in the given circle.

    x and y are the x and y values of the point to be tested. It should be
    given as the numpy index (starting at 0). xcenter and ycenter should also
    be given as numpy indices, and indicate the central coordinate of the
    circle. 
    '''
    xcen = x - xcenter
    ycen = y - ycenter
    return xcen**2 + ycen**2 <= radius**2

def mask_ellipse(image, center, semimajor, semiminor, pa, outputfile):
    '''Masks an elliptical region of the image.

    This function takes an elliptical region of an image and sets it to zero,
    effectively masking it. The center and semimajor axis should be in units of
    pixels. The masked image will then be outputted into outputfile.
    '''
    xcenter, ycenter = center
    command = build_imcalc_ellipse(xcenter, ycenter, semimajor, semiminor, pa)
    run_imcalc(image, outputfile, command)

def build_imcalc_ellipse(xcenter, ycenter, semimajor, semiminor, pa):
    '''Builds the command for creating an ellipse in imcalc.'''
    command = ("if ((x-{xcen})*cos({pa}) + (y-{ycen})*sin({pa}))**2 / {a}**2" +
    " + ((x-{xcen})*sin({pa}) - (y-{ycen})*cos({pa}))**2 / {b}**2 " + 
    " < 1 then 1 else im1").format(xcen=xcenter, ycen=ycenter, a=semiminor,
            b=semimajor, pa=-pa/180.0*math.pi)
    return command


def build_imcalc_circle(xcenter, ycenter, radius):
    '''Builds the command for creating a circle in imcalc.'''
    command = "if (x-{0})**2 + (y-{1})**2 < {2}**2 then 1 else im1".format(
            xcenter, ycenter, radius)
    return command

def run_imcalc(image, output, command, overwrite=True, newformat="old"):
    '''Runs the IRAF imcalc routine.

    This function takes either an image or a list of images, and then runs the 
    command given on them, resulting in an image at the location given by output.

    Imcalc normally avoids overwriting an image and instead places the new image
    as a data cube. This behavior is largely undesired for our purposes. As a
    result, the overwrite flag will delete the previous file and then will place
    the output of imcalc onto the next location. If overwrite is true and the
    output file does not initially exist, this function will behave as expected
    and simply write the file to the destination.
    '''
    # Weird stuff can happen when we're doing a reduction. I.e. the output file
    # is also one of the input files. We'll try to deal with this corner case
    # the best way I know how.
    if output is image:
        newimage = image.rpartition(".")[2] + ".tmp.fits"
        shutil.move(image, newimage)
        image = newimage
    elif output in image:
        reassignindex = image.index(output)
        reassignfile = image[reassignindex]
        newimage = reassignfile.rpartition(".")[2] + ".tmp.fits"
        shutil.move(reassignfile, newimage)
        image[reassignindex] = newimage
    if overwrite:
        try:
            backup = backup_file(output)
        except IOError:
            pass
    iraf.stsdas()
    iraf.toolbox()
    iraf.imgtools()
    if type(image) is list:
        imagestring = ','.join(image)
    else:
        imagestring = image
    try:
        # NOTE: If you get NaN problems, check the command first!
        iraf.imcalc.setParam("pixtype", newformat)
        iraf.imcalc(imagestring, output, command)
    except iraf.IrafError as e:
        if overwrite:
            restore_file(output)
        raise e

def run_imshift(image, output, xshift, yshift):
    '''Runs imshift on the image.'''
    try:
        os.remove(output)
    except OSError:
        pass
    iraf.images()
    iraf.imgeom()
    iraf.imshift(image, output, xshift, yshift)


def run_imarith(arg1, operator, arg2, output):
    '''Runs the IRAF imarith routine.

    This function will take image or value given as arg 1, and then perform a
    binary operation defined by the operator string onto arg2 with it. The
    output image will then be placed at output.
    '''
    if not os.path.isfile(arg1) and not os.path.isfile(arg2):
        raise OSError("Neither argument is a valid path.")
    try:
        os.remove(output)
    except OSError:
        pass
    iraf.images()
    iraf.kmutil()
    iraf.imarith(arg1, operator, arg2, output)

def run_gauss(input, output, sigma):
    '''Performs a gaussian convolution on the input image.'''
    try:
        os.remove(output)
    except OSError:
        pass
    iraf.images()
    iraf.imfilter()
    iraf.gauss(input, output, sigma)

def run_immean(input):
    '''Calculates the mean value of the image given.

    If you only want the mean value of a rectangular section of an image, you
    can pass a slice of the image to only sample the cutout.
    '''
    iraf.stsdas()
    iraf.playpen()
    print input
    iraf.immean(input)
    meanvalue = iraf.immean.getParam("mean")
    return meanvalue

def select_sextractor_config(SEXTRACTOR_PATH, band, imgname):
    '''Picks a sextractor config file for the appropriate band.

    There are different sextractor configs for images from different
    instruments, so this method selects the most appropriate config file.
    '''
    if band in phot.UVBANDS:
        if os.path.basename(imgname).startswith("MIS"):
            configname = "MIS.sex"
        else:
            configname = "UV.sex"
    elif band in phot.IRBANDS:
        configname = "WISE.sex"
    else:
        raise ValueError("Band {0} not recognized".format(band))
    return os.path.join(SEXTRACTOR_PATH, configname)

def backup_file(filepath):
    '''Performs a backup of a file by appending .backup to it. 
    
    Returns the path of the new file.'''
    dest = filepath + ".backup"
    shutil.move(filepath, dest)



def restore_file(filepath):
    '''Restores a file backed up by backup_file().'''
    source = filepath + ".backup"
    os.rename(source, filepath)
